name: DevOps Course
on:
   push:
     branches:[main]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:
        - name:checkout
        - uses:actions/checkout@v5

        - name:'setup Node.js',
        - uses:actions/setup-node@v3
        - with: node-version:22

        - name :'Install Dependencies'
        - run: npm install

        - name :run tests
        - run: npm test



